# ────────────────────────────────────────────────────────────
# dev.app.lucaslopvet.fr  →  Flutter web (branche dev)
# ────────────────────────────────────────────────────────────
server {
    listen 80;
    server_name dev.app.lucaslopvet.fr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dev.app.lucaslopvet.fr;

    ssl_certificate     /etc/letsencrypt/live/dev.app.lucaslopvet.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.app.lucaslopvet.fr/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root  /var/www/flutter-app-dev;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1h;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
